# Generated by Django 3.1 on 2020-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200820_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='comments',
            field=models.ManyToManyField(to='projects.Comment'),
        ),
    ]
